language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssl-dev libcunit1-dev libcppunit-dev
install:
  - ./autogen.sh
script: 
  - mkdir -p build
  - cd build 
  - ../configure --disable-silent-rules
  - make -j 2
  - make -j 2 check
