sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssl-dev libcunit1-dev libcppunit-dev libgoogle-glog-dev clang-format-3.8
install:
  - ./autogen.sh
env:
  - FLAGS="--disable-silent-rules --enable-debug"
  - FLAGS="--disable-silent-rules"
script:
  - mkdir -p build
  - cd build
  - ../configure $FLAGS 
  - find .. -regex '.*\.\(hh?\|cc?\|hpp\|cpp\)$$' | xargs clang-format-3.8 -i -style=file
  - git diff --exit-code
  - make -j 2
  - VERBOSE=yes make -j 2 check
branches:
  only:
    - master
    - stable
notifications:
  email:
    - andreas.koepsel@bisdn.de
